Add docstrings #56
allenai/ScienceWorld pull request #66
Opened 2024-01-14 20:23 UTC by AndKaminer

Added docstrings. In the future, I'm going to add type hinting, which will make the docstrings more clear. I think a higher level documentation page or two might be helpful, which I will work on after type hinting.

2024-01-17 21:33 UTC, AndKaminer commented
@MarcCote Hopefully this should be good. Thanks!

2024-01-22 01:22 UTC, MarcCote requested changes
Great work! I made a couple of change requests but otherwise LGTM.

2024-01-22 01:22 UTC, MarcCote commented on scienceworld/scienceworld.py
> +        '''Gets the 6 possible simplifications. There are 6 simplifictions:
```suggestion
        '''Gets the 6 possible simplifications. Those are:
```

2024-01-22 01:22 UTC, MarcCote commented on scienceworld/scienceworld.py
> +            - teleportAction: Teleport action
```suggestion
            - teleportAction: Adds actions to teleport directly to any possible location
```

2024-01-22 01:22 UTC, MarcCote commented on scienceworld/scienceworld.py
> +            - selfWateringFlowerPots: Self-watering flower pots
```suggestion
            - selfWateringFlowerPots: Flower pots will water themselves such that the plants won't die
```

2024-01-22 01:22 UTC, MarcCote commented on scienceworld/scienceworld.py
> +            - openContainers: Containers open by default
```suggestion
            - openContainers: Containers are open by default
```

2024-01-22 01:22 UTC, MarcCote commented on scienceworld/scienceworld.py
> +            - openDoors: Doors open by default
```suggestion
            - openDoors: Doors open are by default
```

2024-01-22 01:22 UTC, MarcCote commented on scienceworld/scienceworld.py
> +            - noElectricalAction: Remove the electrical actions
```suggestion
            - noElectricalAction: Remove all `connect X to Y` actions to reduce the action space
```

2024-01-22 01:22 UTC, MarcCote commented on scienceworld/scienceworld.py
> +            - easy: use all 5 simplifications
```suggestion
            - easy: use all above simplifications
```

2024-01-22 01:22 UTC, MarcCote commented on scienceworld/scienceworld.py
>      # Get possible actions
We can remove all of those comments that were meant to act as docstring.

2024-01-22 01:22 UTC, MarcCote commented on scienceworld/scienceworld.py
> +        The gold action sequence is the optimal sequence of actions. This function returns that if it is generated.
```suggestion
        The gold action sequence is a sequence of actions that leads to a winning state (there is no guarantee it is the optimal). This function returns that if it is generated.
```

2024-01-23 13:08 UTC, AndKaminer commented
Okay that should be good. Sorry you had to fix my dumb grammar mistakes haha

2024-01-25 18:11 UTC, merged